#include <windows.h>
#include <commctrl.h>
#include <algorithm>
#include <array>
#include <atomic>
#include <string>
#include <thread>
#include <vector>
#include "protocol.h"
namespace {
enum{IDC_LIST=1001,IDC_REFRESH,IDC_RUN,IDC_STOP,IDC_RESET,IDC_REPEAT,IDC_GAP,IDC_HOLD,IDC_STATUS};
HINSTANCE g_instance{};HWND g_main{},g_list{},g_run{},g_repeat{},g_gap{},g_hold{},g_status{};
std::array<HWND,4> g_labels{};std::array<POINT,4> g_points{{{2500,4700},{7500,4700},{2500,6800},{7500,6800}}};
std::vector<DWORD> g_pids;std::atomic_bool g_running{},g_paused{};std::atomic_uint64_t g_sequence{};
BOOL CALLBACK EnumTarget(HWND h,LPARAM){wchar_t c[128]{};GetClassNameW(h,c,128);if(lstrcmpW(c,vilab::kTargetClass))return TRUE;DWORD p{};GetWindowThreadProcessId(h,&p);if(p)g_pids.push_back(p);return TRUE;}
void Column(int i,int w,const wchar_t*n){LVCOLUMNW c{};c.mask=LVCF_TEXT|LVCF_WIDTH;c.cx=w;c.pszText=const_cast<wchar_t*>(n);ListView_InsertColumn(g_list,i,&c);}
void Refresh(){g_pids.clear();EnumWindows(EnumTarget,0);ListView_DeleteAllItems(g_list);for(size_t i=0;i<g_pids.size();++i){std::wstring n=std::to_wstring(i+1);LVITEMW v{};v.mask=LVIF_TEXT;v.iItem=static_cast<int>(i);v.pszText=n.data();int row=ListView_InsertItem(g_list,&v);std::wstring p=std::to_wstring(g_pids[i]);ListView_SetItemText(g_list,row,1,p.data());ListView_SetCheckState(g_list,row,TRUE);}}
int ReadInt(HWND h,int f){wchar_t b[32]{};GetWindowTextW(h,b,32);wchar_t*e{};long v=wcstol(b,&e,10);return e==b?f:static_cast<int>(v);}
std::vector<DWORD> Selected(){std::vector<DWORD>v;for(int i=0;i<ListView_GetItemCount(g_list);++i)if(ListView_GetCheckState(g_list,i)&&i<static_cast<int>(g_pids.size()))v.push_back(g_pids[i]);return v;}
bool SendTo(DWORD pid,const vilab::Command&c,DWORD&ms){ULONGLONG start=GetTickCount64();std::wstring n=std::wstring(vilab::kPipePrefix)+std::to_wstring(pid);if(!WaitNamedPipeW(n.c_str(),120)){ms=static_cast<DWORD>(GetTickCount64()-start);return false;}HANDLE p=CreateFileW(n.c_str(),GENERIC_WRITE,0,nullptr,OPEN_EXISTING,0,nullptr);if(p==INVALID_HANDLE_VALUE){ms=static_cast<DWORD>(GetTickCount64()-start);return false;}DWORD w{};bool ok=WriteFile(p,&c,sizeof(c),&w,nullptr)&&w==sizeof(c);CloseHandle(p);ms=static_cast<DWORD>(GetTickCount64()-start);return ok;}
void Log(DWORD pid,const vilab::Command&c,bool ok,DWORD ms){HANDLE f=CreateFileW(L"VirtualInputLab_V3_log.csv",FILE_APPEND_DATA,FILE_SHARE_READ|FILE_SHARE_WRITE,nullptr,OPEN_ALWAYS,FILE_ATTRIBUTE_NORMAL,nullptr);if(f==INVALID_HANDLE_VALUE)return;std::string s=std::to_string(GetTickCount64())+","+std::to_string(pid)+","+std::to_string(c.sequence)+","+std::to_string(c.step)+","+std::to_string(static_cast<unsigned>(c.type))+","+(ok?"OK":"FAIL")+","+std::to_string(ms)+"\r\n";DWORD n{};WriteFile(f,s.data(),static_cast<DWORD>(s.size()),&n,nullptr);CloseHandle(f);}
void Parallel(const std::vector<DWORD>&p,const vilab::Command&c){std::vector<std::thread>w;for(DWORD id:p)w.emplace_back([id,c]{DWORD ms{};bool ok=SendTo(id,c,ms);Log(id,c,ok,ms);});for(auto&t:w)t.join();}
vilab::Command Cmd(vilab::CommandType t,POINT p,unsigned step,std::uint64_t seq){vilab::Command c{};c.type=t;c.x=p.x;c.y=p.y;c.step=step;c.sequence=seq;return c;}
void ClickStep(const std::vector<DWORD>&p,int i,int hold){auto seq=++g_sequence;POINT q=g_points[i];Parallel(p,Cmd(vilab::CommandType::Move,q,i+1,seq));Parallel(p,Cmd(vilab::CommandType::LeftDown,q,i+1,seq));Sleep(static_cast<DWORD>(hold));Parallel(p,Cmd(vilab::CommandType::LeftUp,q,i+1,seq));}
void Label(int i){std::wstring s=L"F"+std::to_wstring(i+1)+L": X="+std::to_wstring(g_points[i].x)+L" Y="+std::to_wstring(g_points[i].y);SetWindowTextW(g_labels[i],s.c_str());}
void Capture(int i){POINT s{};GetCursorPos(&s);HWND h=WindowFromPoint(s);wchar_t c[128]{};GetClassNameW(h,c,128);if(lstrcmpW(c,vilab::kTargetClass)){SetWindowTextW(g_status,L"Dat chuot trong Target V3 roi nhan F1-F4.");return;}RECT r{};GetClientRect(h,&r);POINT p=s;ScreenToClient(h,&p);g_points[i].x=std::clamp<LONG>(MulDiv(p.x,10000,std::max(1L,r.right)),0L,10000L);g_points[i].y=std::clamp<LONG>(MulDiv(p.y,10000,std::max(1L,r.bottom)),0L,10000L);Label(i);SetWindowTextW(g_status,L"Da luu diem.");}
void Toggle(){if(g_running){g_paused=!g_paused;SetWindowTextW(g_run,g_paused?L"Tiep tuc":L"Tam dung");return;}auto p=Selected();if(p.empty()){SetWindowTextW(g_status,L"Chua chon Target.");return;}int repeat=std::clamp(ReadInt(g_repeat,10),1,99999),gap=std::clamp(ReadInt(g_gap,250),20,600000),hold=std::clamp(ReadInt(g_hold,80),1,500);g_running=true;g_paused=false;SetWindowTextW(g_run,L"Tam dung");std::thread([p,repeat,gap,hold]{for(int r=0;r<repeat&&g_running;++r)for(int s=0;s<4&&g_running;++s){while(g_paused&&g_running)Sleep(20);if(!g_running)break;ClickStep(p,s,hold);for(int n=0;n<gap&&g_running;n+=20)Sleep(20);}g_running=false;g_paused=false;PostMessageW(g_main,WM_APP+1,0,0);}).detach();}
void Stop(){g_running=false;g_paused=false;SetWindowTextW(g_run,L"Bat dau 1-2-3-4");SetWindowTextW(g_status,L"Da dung.");}
void Reset(){auto p=Selected();vilab::Command c{};c.type=vilab::CommandType::Reset;c.sequence=++g_sequence;Parallel(p,c);}
LRESULT CALLBACK Proc(HWND h,UINT m,WPARAM w,LPARAM l){if(m==WM_CREATE){CreateWindowW(L"BUTTON",L"Lam moi danh sach",WS_CHILD|WS_VISIBLE,14,14,160,28,h,reinterpret_cast<HMENU>(IDC_REFRESH),g_instance,nullptr);g_list=CreateWindowExW(WS_EX_CLIENTEDGE,WC_LISTVIEWW,L"",WS_CHILD|WS_VISIBLE|LVS_REPORT,14,50,300,430,h,reinterpret_cast<HMENU>(IDC_LIST),g_instance,nullptr);ListView_SetExtendedListViewStyle(g_list,LVS_EX_CHECKBOXES|LVS_EX_FULLROWSELECT|LVS_EX_GRIDLINES);Column(0,70,L"#");Column(1,190,L"PID Target V3");CreateWindowW(L"STATIC",L"Dat chuot len Target mau, nhan F1-F4 de lay diem",WS_CHILD|WS_VISIBLE,335,18,390,24,h,nullptr,g_instance,nullptr);for(int i=0;i<4;++i){g_labels[i]=CreateWindowW(L"STATIC",L"",WS_CHILD|WS_VISIBLE,345,55+i*32,230,24,h,nullptr,g_instance,nullptr);Label(i);}CreateWindowW(L"STATIC",L"Giu nut (ms):",WS_CHILD|WS_VISIBLE,345,196,110,24,h,nullptr,g_instance,nullptr);g_hold=CreateWindowExW(WS_EX_CLIENTEDGE,L"EDIT",L"80",WS_CHILD|WS_VISIBLE|ES_NUMBER,465,192,110,26,h,reinterpret_cast<HMENU>(IDC_HOLD),g_instance,nullptr);CreateWindowW(L"STATIC",L"Gian cach diem (ms):",WS_CHILD|WS_VISIBLE,345,232,140,24,h,nullptr,g_instance,nullptr);g_gap=CreateWindowExW(WS_EX_CLIENTEDGE,L"EDIT",L"250",WS_CHILD|WS_VISIBLE|ES_NUMBER,490,228,85,26,h,reinterpret_cast<HMENU>(IDC_GAP),g_instance,nullptr);CreateWindowW(L"STATIC",L"So vong:",WS_CHILD|WS_VISIBLE,345,268,85,24,h,nullptr,g_instance,nullptr);g_repeat=CreateWindowExW(WS_EX_CLIENTEDGE,L"EDIT",L"10",WS_CHILD|WS_VISIBLE|ES_NUMBER,435,264,140,26,h,reinterpret_cast<HMENU>(IDC_REPEAT),g_instance,nullptr);g_run=CreateWindowW(L"BUTTON",L"Bat dau 1-2-3-4",WS_CHILD|WS_VISIBLE,345,310,230,34,h,reinterpret_cast<HMENU>(IDC_RUN),g_instance,nullptr);CreateWindowW(L"BUTTON",L"Dung",WS_CHILD|WS_VISIBLE,585,310,120,34,h,reinterpret_cast<HMENU>(IDC_STOP),g_instance,nullptr);CreateWindowW(L"BUTTON",L"Dat lai bo dem",WS_CHILD|WS_VISIBLE,345,352,230,32,h,reinterpret_cast<HMENU>(IDC_RESET),g_instance,nullptr);g_status=CreateWindowW(L"STATIC",L"San sang. Log: VirtualInputLab_V3_log.csv",WS_CHILD|WS_VISIBLE|SS_LEFT,345,402,370,55,h,reinterpret_cast<HMENU>(IDC_STATUS),g_instance,nullptr);for(int i=0;i<4;++i)RegisterHotKey(h,i+1,0,VK_F1+i);Refresh();return 0;}if(m==WM_HOTKEY){Capture(static_cast<int>(w)-1);return 0;}if(m==WM_COMMAND){switch(LOWORD(w)){case IDC_REFRESH:Refresh();return 0;case IDC_RUN:Toggle();return 0;case IDC_STOP:Stop();return 0;case IDC_RESET:Reset();return 0;}}if(m==WM_APP+1){SetWindowTextW(g_run,L"Bat dau 1-2-3-4");SetWindowTextW(g_status,L"Da chay xong kich ban.");return 0;}if(m==WM_DESTROY){g_running=false;for(int i=0;i<4;++i)UnregisterHotKey(h,i+1);PostQuitMessage(0);return 0;}return DefWindowProcW(h,m,w,l);}
}
int WINAPI wWinMain(HINSTANCE i,HINSTANCE,PWSTR,int show){g_instance=i;INITCOMMONCONTROLSEX cc{sizeof(cc),ICC_LISTVIEW_CLASSES};InitCommonControlsEx(&cc);WNDCLASSEXW wc{sizeof(wc)};wc.hInstance=i;wc.lpfnWndProc=Proc;wc.lpszClassName=L"VirtualInputLab.Controller.V3";wc.hCursor=LoadCursorW(nullptr,IDC_ARROW);wc.hbrBackground=reinterpret_cast<HBRUSH>(COLOR_BTNFACE+1);RegisterClassExW(&wc);g_main=CreateWindowExW(0,wc.lpszClassName,L"Virtual Input Lab V3 - Bo dieu khien",WS_OVERLAPPED|WS_CAPTION|WS_SYSMENU|WS_MINIMIZEBOX,CW_USEDEFAULT,CW_USEDEFAULT,750,535,nullptr,nullptr,i,nullptr);if(!g_main)return 1;ShowWindow(g_main,show);UpdateWindow(g_main);MSG msg{};while(GetMessageW(&msg,nullptr,0,0)>0){TranslateMessage(&msg);DispatchMessageW(&msg);}return static_cast<int>(msg.wParam);}
